<div class="container">
    <div class="row">
        <div class="col-6">
            <h2>
                <a class="d-inline-flex align-items-center login-text" href="<?= $block->getUrl('customer/account/login') ?>">
                    <i class="fas fa-user-tie pr-2"></i>
                    <?= _("Login") ?>
            
                </a>
            </h2>
            
        </div>
        <div class="col-6">
        <h2>
                <a class="d-inline-flex align-items-center create-text" href="<?= $block->getUrl('customer/account/create') ?>">
                    <i class="fas fa-address-card    pr-2"></i>
                    <?= _("Create ") ?>
                </a>
            </h2>
        </div>
    </div>
</div>